// Code generated by protoc-gen-go. DO NOT EDIT.
// source: replica.proto

package ptypes

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReplicaCreateRequest struct {
	Size                 string   `protobuf:"bytes,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaCreateRequest) Reset()         { *m = ReplicaCreateRequest{} }
func (m *ReplicaCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ReplicaCreateRequest) ProtoMessage()    {}
func (*ReplicaCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{0}
}

func (m *ReplicaCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaCreateRequest.Unmarshal(m, b)
}
func (m *ReplicaCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaCreateRequest.Marshal(b, m, deterministic)
}
func (m *ReplicaCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaCreateRequest.Merge(m, src)
}
func (m *ReplicaCreateRequest) XXX_Size() int {
	return xxx_messageInfo_ReplicaCreateRequest.Size(m)
}
func (m *ReplicaCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaCreateRequest proto.InternalMessageInfo

func (m *ReplicaCreateRequest) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

type ReplicaCreateResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaCreateResponse) Reset()         { *m = ReplicaCreateResponse{} }
func (m *ReplicaCreateResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicaCreateResponse) ProtoMessage()    {}
func (*ReplicaCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{1}
}

func (m *ReplicaCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaCreateResponse.Unmarshal(m, b)
}
func (m *ReplicaCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaCreateResponse.Marshal(b, m, deterministic)
}
func (m *ReplicaCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaCreateResponse.Merge(m, src)
}
func (m *ReplicaCreateResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicaCreateResponse.Size(m)
}
func (m *ReplicaCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaCreateResponse proto.InternalMessageInfo

func (m *ReplicaCreateResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type ReplicaGetResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaGetResponse) Reset()         { *m = ReplicaGetResponse{} }
func (m *ReplicaGetResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicaGetResponse) ProtoMessage()    {}
func (*ReplicaGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{2}
}

func (m *ReplicaGetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaGetResponse.Unmarshal(m, b)
}
func (m *ReplicaGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaGetResponse.Marshal(b, m, deterministic)
}
func (m *ReplicaGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaGetResponse.Merge(m, src)
}
func (m *ReplicaGetResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicaGetResponse.Size(m)
}
func (m *ReplicaGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaGetResponse proto.InternalMessageInfo

func (m *ReplicaGetResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type ReplicaOpenResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaOpenResponse) Reset()         { *m = ReplicaOpenResponse{} }
func (m *ReplicaOpenResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicaOpenResponse) ProtoMessage()    {}
func (*ReplicaOpenResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{3}
}

func (m *ReplicaOpenResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaOpenResponse.Unmarshal(m, b)
}
func (m *ReplicaOpenResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaOpenResponse.Marshal(b, m, deterministic)
}
func (m *ReplicaOpenResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaOpenResponse.Merge(m, src)
}
func (m *ReplicaOpenResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicaOpenResponse.Size(m)
}
func (m *ReplicaOpenResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaOpenResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaOpenResponse proto.InternalMessageInfo

func (m *ReplicaOpenResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type ReplicaCloseResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaCloseResponse) Reset()         { *m = ReplicaCloseResponse{} }
func (m *ReplicaCloseResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicaCloseResponse) ProtoMessage()    {}
func (*ReplicaCloseResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{4}
}

func (m *ReplicaCloseResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaCloseResponse.Unmarshal(m, b)
}
func (m *ReplicaCloseResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaCloseResponse.Marshal(b, m, deterministic)
}
func (m *ReplicaCloseResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaCloseResponse.Merge(m, src)
}
func (m *ReplicaCloseResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicaCloseResponse.Size(m)
}
func (m *ReplicaCloseResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaCloseResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaCloseResponse proto.InternalMessageInfo

func (m *ReplicaCloseResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type ReplicaReloadResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaReloadResponse) Reset()         { *m = ReplicaReloadResponse{} }
func (m *ReplicaReloadResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicaReloadResponse) ProtoMessage()    {}
func (*ReplicaReloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{5}
}

func (m *ReplicaReloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaReloadResponse.Unmarshal(m, b)
}
func (m *ReplicaReloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaReloadResponse.Marshal(b, m, deterministic)
}
func (m *ReplicaReloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaReloadResponse.Merge(m, src)
}
func (m *ReplicaReloadResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicaReloadResponse.Size(m)
}
func (m *ReplicaReloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaReloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaReloadResponse proto.InternalMessageInfo

func (m *ReplicaReloadResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type ReplicaRevertRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Created              string   `protobuf:"bytes,2,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaRevertRequest) Reset()         { *m = ReplicaRevertRequest{} }
func (m *ReplicaRevertRequest) String() string { return proto.CompactTextString(m) }
func (*ReplicaRevertRequest) ProtoMessage()    {}
func (*ReplicaRevertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{6}
}

func (m *ReplicaRevertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaRevertRequest.Unmarshal(m, b)
}
func (m *ReplicaRevertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaRevertRequest.Marshal(b, m, deterministic)
}
func (m *ReplicaRevertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaRevertRequest.Merge(m, src)
}
func (m *ReplicaRevertRequest) XXX_Size() int {
	return xxx_messageInfo_ReplicaRevertRequest.Size(m)
}
func (m *ReplicaRevertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaRevertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaRevertRequest proto.InternalMessageInfo

func (m *ReplicaRevertRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReplicaRevertRequest) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

type ReplicaRevertResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaRevertResponse) Reset()         { *m = ReplicaRevertResponse{} }
func (m *ReplicaRevertResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicaRevertResponse) ProtoMessage()    {}
func (*ReplicaRevertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{7}
}

func (m *ReplicaRevertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaRevertResponse.Unmarshal(m, b)
}
func (m *ReplicaRevertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaRevertResponse.Marshal(b, m, deterministic)
}
func (m *ReplicaRevertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaRevertResponse.Merge(m, src)
}
func (m *ReplicaRevertResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicaRevertResponse.Size(m)
}
func (m *ReplicaRevertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaRevertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaRevertResponse proto.InternalMessageInfo

func (m *ReplicaRevertResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type ReplicaSnapshotRequest struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	UserCreated          bool              `protobuf:"varint,2,opt,name=user_created,json=userCreated,proto3" json:"user_created,omitempty"`
	Created              string            `protobuf:"bytes,3,opt,name=created,proto3" json:"created,omitempty"`
	Labels               map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ReplicaSnapshotRequest) Reset()         { *m = ReplicaSnapshotRequest{} }
func (m *ReplicaSnapshotRequest) String() string { return proto.CompactTextString(m) }
func (*ReplicaSnapshotRequest) ProtoMessage()    {}
func (*ReplicaSnapshotRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{8}
}

func (m *ReplicaSnapshotRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaSnapshotRequest.Unmarshal(m, b)
}
func (m *ReplicaSnapshotRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaSnapshotRequest.Marshal(b, m, deterministic)
}
func (m *ReplicaSnapshotRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaSnapshotRequest.Merge(m, src)
}
func (m *ReplicaSnapshotRequest) XXX_Size() int {
	return xxx_messageInfo_ReplicaSnapshotRequest.Size(m)
}
func (m *ReplicaSnapshotRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaSnapshotRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaSnapshotRequest proto.InternalMessageInfo

func (m *ReplicaSnapshotRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReplicaSnapshotRequest) GetUserCreated() bool {
	if m != nil {
		return m.UserCreated
	}
	return false
}

func (m *ReplicaSnapshotRequest) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *ReplicaSnapshotRequest) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ReplicaSnapshotResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaSnapshotResponse) Reset()         { *m = ReplicaSnapshotResponse{} }
func (m *ReplicaSnapshotResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicaSnapshotResponse) ProtoMessage()    {}
func (*ReplicaSnapshotResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{9}
}

func (m *ReplicaSnapshotResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaSnapshotResponse.Unmarshal(m, b)
}
func (m *ReplicaSnapshotResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaSnapshotResponse.Marshal(b, m, deterministic)
}
func (m *ReplicaSnapshotResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaSnapshotResponse.Merge(m, src)
}
func (m *ReplicaSnapshotResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicaSnapshotResponse.Size(m)
}
func (m *ReplicaSnapshotResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaSnapshotResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaSnapshotResponse proto.InternalMessageInfo

func (m *ReplicaSnapshotResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type ReplicaExpandRequest struct {
	Size                 int64    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaExpandRequest) Reset()         { *m = ReplicaExpandRequest{} }
func (m *ReplicaExpandRequest) String() string { return proto.CompactTextString(m) }
func (*ReplicaExpandRequest) ProtoMessage()    {}
func (*ReplicaExpandRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{10}
}

func (m *ReplicaExpandRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaExpandRequest.Unmarshal(m, b)
}
func (m *ReplicaExpandRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaExpandRequest.Marshal(b, m, deterministic)
}
func (m *ReplicaExpandRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaExpandRequest.Merge(m, src)
}
func (m *ReplicaExpandRequest) XXX_Size() int {
	return xxx_messageInfo_ReplicaExpandRequest.Size(m)
}
func (m *ReplicaExpandRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaExpandRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaExpandRequest proto.InternalMessageInfo

func (m *ReplicaExpandRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type ReplicaExpandResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplicaExpandResponse) Reset()         { *m = ReplicaExpandResponse{} }
func (m *ReplicaExpandResponse) String() string { return proto.CompactTextString(m) }
func (*ReplicaExpandResponse) ProtoMessage()    {}
func (*ReplicaExpandResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{11}
}

func (m *ReplicaExpandResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplicaExpandResponse.Unmarshal(m, b)
}
func (m *ReplicaExpandResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplicaExpandResponse.Marshal(b, m, deterministic)
}
func (m *ReplicaExpandResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplicaExpandResponse.Merge(m, src)
}
func (m *ReplicaExpandResponse) XXX_Size() int {
	return xxx_messageInfo_ReplicaExpandResponse.Size(m)
}
func (m *ReplicaExpandResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplicaExpandResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReplicaExpandResponse proto.InternalMessageInfo

func (m *ReplicaExpandResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type DiskRemoveRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Force                bool     `protobuf:"varint,2,opt,name=force,proto3" json:"force,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskRemoveRequest) Reset()         { *m = DiskRemoveRequest{} }
func (m *DiskRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*DiskRemoveRequest) ProtoMessage()    {}
func (*DiskRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{12}
}

func (m *DiskRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskRemoveRequest.Unmarshal(m, b)
}
func (m *DiskRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskRemoveRequest.Marshal(b, m, deterministic)
}
func (m *DiskRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskRemoveRequest.Merge(m, src)
}
func (m *DiskRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_DiskRemoveRequest.Size(m)
}
func (m *DiskRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiskRemoveRequest proto.InternalMessageInfo

func (m *DiskRemoveRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DiskRemoveRequest) GetForce() bool {
	if m != nil {
		return m.Force
	}
	return false
}

type DiskRemoveResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskRemoveResponse) Reset()         { *m = DiskRemoveResponse{} }
func (m *DiskRemoveResponse) String() string { return proto.CompactTextString(m) }
func (*DiskRemoveResponse) ProtoMessage()    {}
func (*DiskRemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{13}
}

func (m *DiskRemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskRemoveResponse.Unmarshal(m, b)
}
func (m *DiskRemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskRemoveResponse.Marshal(b, m, deterministic)
}
func (m *DiskRemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskRemoveResponse.Merge(m, src)
}
func (m *DiskRemoveResponse) XXX_Size() int {
	return xxx_messageInfo_DiskRemoveResponse.Size(m)
}
func (m *DiskRemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskRemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiskRemoveResponse proto.InternalMessageInfo

func (m *DiskRemoveResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type DiskReplaceRequest struct {
	Target               string   `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskReplaceRequest) Reset()         { *m = DiskReplaceRequest{} }
func (m *DiskReplaceRequest) String() string { return proto.CompactTextString(m) }
func (*DiskReplaceRequest) ProtoMessage()    {}
func (*DiskReplaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{14}
}

func (m *DiskReplaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskReplaceRequest.Unmarshal(m, b)
}
func (m *DiskReplaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskReplaceRequest.Marshal(b, m, deterministic)
}
func (m *DiskReplaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskReplaceRequest.Merge(m, src)
}
func (m *DiskReplaceRequest) XXX_Size() int {
	return xxx_messageInfo_DiskReplaceRequest.Size(m)
}
func (m *DiskReplaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskReplaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiskReplaceRequest proto.InternalMessageInfo

func (m *DiskReplaceRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func (m *DiskReplaceRequest) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

type DiskReplaceResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskReplaceResponse) Reset()         { *m = DiskReplaceResponse{} }
func (m *DiskReplaceResponse) String() string { return proto.CompactTextString(m) }
func (*DiskReplaceResponse) ProtoMessage()    {}
func (*DiskReplaceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{15}
}

func (m *DiskReplaceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskReplaceResponse.Unmarshal(m, b)
}
func (m *DiskReplaceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskReplaceResponse.Marshal(b, m, deterministic)
}
func (m *DiskReplaceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskReplaceResponse.Merge(m, src)
}
func (m *DiskReplaceResponse) XXX_Size() int {
	return xxx_messageInfo_DiskReplaceResponse.Size(m)
}
func (m *DiskReplaceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskReplaceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiskReplaceResponse proto.InternalMessageInfo

func (m *DiskReplaceResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type DiskPrepareRemoveRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskPrepareRemoveRequest) Reset()         { *m = DiskPrepareRemoveRequest{} }
func (m *DiskPrepareRemoveRequest) String() string { return proto.CompactTextString(m) }
func (*DiskPrepareRemoveRequest) ProtoMessage()    {}
func (*DiskPrepareRemoveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{16}
}

func (m *DiskPrepareRemoveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskPrepareRemoveRequest.Unmarshal(m, b)
}
func (m *DiskPrepareRemoveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskPrepareRemoveRequest.Marshal(b, m, deterministic)
}
func (m *DiskPrepareRemoveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskPrepareRemoveRequest.Merge(m, src)
}
func (m *DiskPrepareRemoveRequest) XXX_Size() int {
	return xxx_messageInfo_DiskPrepareRemoveRequest.Size(m)
}
func (m *DiskPrepareRemoveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskPrepareRemoveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiskPrepareRemoveRequest proto.InternalMessageInfo

func (m *DiskPrepareRemoveRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DiskPrepareRemoveResponse struct {
	Operations           []*PrepareRemoveAction `protobuf:"bytes,1,rep,name=operations,proto3" json:"operations,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *DiskPrepareRemoveResponse) Reset()         { *m = DiskPrepareRemoveResponse{} }
func (m *DiskPrepareRemoveResponse) String() string { return proto.CompactTextString(m) }
func (*DiskPrepareRemoveResponse) ProtoMessage()    {}
func (*DiskPrepareRemoveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{17}
}

func (m *DiskPrepareRemoveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskPrepareRemoveResponse.Unmarshal(m, b)
}
func (m *DiskPrepareRemoveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskPrepareRemoveResponse.Marshal(b, m, deterministic)
}
func (m *DiskPrepareRemoveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskPrepareRemoveResponse.Merge(m, src)
}
func (m *DiskPrepareRemoveResponse) XXX_Size() int {
	return xxx_messageInfo_DiskPrepareRemoveResponse.Size(m)
}
func (m *DiskPrepareRemoveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskPrepareRemoveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiskPrepareRemoveResponse proto.InternalMessageInfo

func (m *DiskPrepareRemoveResponse) GetOperations() []*PrepareRemoveAction {
	if m != nil {
		return m.Operations
	}
	return nil
}

type DiskMarkAsRemovedRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskMarkAsRemovedRequest) Reset()         { *m = DiskMarkAsRemovedRequest{} }
func (m *DiskMarkAsRemovedRequest) String() string { return proto.CompactTextString(m) }
func (*DiskMarkAsRemovedRequest) ProtoMessage()    {}
func (*DiskMarkAsRemovedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{18}
}

func (m *DiskMarkAsRemovedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskMarkAsRemovedRequest.Unmarshal(m, b)
}
func (m *DiskMarkAsRemovedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskMarkAsRemovedRequest.Marshal(b, m, deterministic)
}
func (m *DiskMarkAsRemovedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskMarkAsRemovedRequest.Merge(m, src)
}
func (m *DiskMarkAsRemovedRequest) XXX_Size() int {
	return xxx_messageInfo_DiskMarkAsRemovedRequest.Size(m)
}
func (m *DiskMarkAsRemovedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskMarkAsRemovedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiskMarkAsRemovedRequest proto.InternalMessageInfo

func (m *DiskMarkAsRemovedRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type DiskMarkAsRemovedResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiskMarkAsRemovedResponse) Reset()         { *m = DiskMarkAsRemovedResponse{} }
func (m *DiskMarkAsRemovedResponse) String() string { return proto.CompactTextString(m) }
func (*DiskMarkAsRemovedResponse) ProtoMessage()    {}
func (*DiskMarkAsRemovedResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{19}
}

func (m *DiskMarkAsRemovedResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskMarkAsRemovedResponse.Unmarshal(m, b)
}
func (m *DiskMarkAsRemovedResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskMarkAsRemovedResponse.Marshal(b, m, deterministic)
}
func (m *DiskMarkAsRemovedResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskMarkAsRemovedResponse.Merge(m, src)
}
func (m *DiskMarkAsRemovedResponse) XXX_Size() int {
	return xxx_messageInfo_DiskMarkAsRemovedResponse.Size(m)
}
func (m *DiskMarkAsRemovedResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskMarkAsRemovedResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiskMarkAsRemovedResponse proto.InternalMessageInfo

func (m *DiskMarkAsRemovedResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type RebuildingSetRequest struct {
	Rebuilding           bool     `protobuf:"varint,1,opt,name=rebuilding,proto3" json:"rebuilding,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RebuildingSetRequest) Reset()         { *m = RebuildingSetRequest{} }
func (m *RebuildingSetRequest) String() string { return proto.CompactTextString(m) }
func (*RebuildingSetRequest) ProtoMessage()    {}
func (*RebuildingSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{20}
}

func (m *RebuildingSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RebuildingSetRequest.Unmarshal(m, b)
}
func (m *RebuildingSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RebuildingSetRequest.Marshal(b, m, deterministic)
}
func (m *RebuildingSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RebuildingSetRequest.Merge(m, src)
}
func (m *RebuildingSetRequest) XXX_Size() int {
	return xxx_messageInfo_RebuildingSetRequest.Size(m)
}
func (m *RebuildingSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RebuildingSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RebuildingSetRequest proto.InternalMessageInfo

func (m *RebuildingSetRequest) GetRebuilding() bool {
	if m != nil {
		return m.Rebuilding
	}
	return false
}

type RebuildingSetResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RebuildingSetResponse) Reset()         { *m = RebuildingSetResponse{} }
func (m *RebuildingSetResponse) String() string { return proto.CompactTextString(m) }
func (*RebuildingSetResponse) ProtoMessage()    {}
func (*RebuildingSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{21}
}

func (m *RebuildingSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RebuildingSetResponse.Unmarshal(m, b)
}
func (m *RebuildingSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RebuildingSetResponse.Marshal(b, m, deterministic)
}
func (m *RebuildingSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RebuildingSetResponse.Merge(m, src)
}
func (m *RebuildingSetResponse) XXX_Size() int {
	return xxx_messageInfo_RebuildingSetResponse.Size(m)
}
func (m *RebuildingSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RebuildingSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RebuildingSetResponse proto.InternalMessageInfo

func (m *RebuildingSetResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type RevisionCounterSetRequest struct {
	Counter              int64    `protobuf:"varint,1,opt,name=counter,proto3" json:"counter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevisionCounterSetRequest) Reset()         { *m = RevisionCounterSetRequest{} }
func (m *RevisionCounterSetRequest) String() string { return proto.CompactTextString(m) }
func (*RevisionCounterSetRequest) ProtoMessage()    {}
func (*RevisionCounterSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{22}
}

func (m *RevisionCounterSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevisionCounterSetRequest.Unmarshal(m, b)
}
func (m *RevisionCounterSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevisionCounterSetRequest.Marshal(b, m, deterministic)
}
func (m *RevisionCounterSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevisionCounterSetRequest.Merge(m, src)
}
func (m *RevisionCounterSetRequest) XXX_Size() int {
	return xxx_messageInfo_RevisionCounterSetRequest.Size(m)
}
func (m *RevisionCounterSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RevisionCounterSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RevisionCounterSetRequest proto.InternalMessageInfo

func (m *RevisionCounterSetRequest) GetCounter() int64 {
	if m != nil {
		return m.Counter
	}
	return 0
}

type RevisionCounterSetResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RevisionCounterSetResponse) Reset()         { *m = RevisionCounterSetResponse{} }
func (m *RevisionCounterSetResponse) String() string { return proto.CompactTextString(m) }
func (*RevisionCounterSetResponse) ProtoMessage()    {}
func (*RevisionCounterSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{23}
}

func (m *RevisionCounterSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RevisionCounterSetResponse.Unmarshal(m, b)
}
func (m *RevisionCounterSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RevisionCounterSetResponse.Marshal(b, m, deterministic)
}
func (m *RevisionCounterSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RevisionCounterSetResponse.Merge(m, src)
}
func (m *RevisionCounterSetResponse) XXX_Size() int {
	return xxx_messageInfo_RevisionCounterSetResponse.Size(m)
}
func (m *RevisionCounterSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RevisionCounterSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RevisionCounterSetResponse proto.InternalMessageInfo

func (m *RevisionCounterSetResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type UnmapMarkDiskChainRemovedSetRequest struct {
	Enabled              bool     `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnmapMarkDiskChainRemovedSetRequest) Reset()         { *m = UnmapMarkDiskChainRemovedSetRequest{} }
func (m *UnmapMarkDiskChainRemovedSetRequest) String() string { return proto.CompactTextString(m) }
func (*UnmapMarkDiskChainRemovedSetRequest) ProtoMessage()    {}
func (*UnmapMarkDiskChainRemovedSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{24}
}

func (m *UnmapMarkDiskChainRemovedSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnmapMarkDiskChainRemovedSetRequest.Unmarshal(m, b)
}
func (m *UnmapMarkDiskChainRemovedSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnmapMarkDiskChainRemovedSetRequest.Marshal(b, m, deterministic)
}
func (m *UnmapMarkDiskChainRemovedSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnmapMarkDiskChainRemovedSetRequest.Merge(m, src)
}
func (m *UnmapMarkDiskChainRemovedSetRequest) XXX_Size() int {
	return xxx_messageInfo_UnmapMarkDiskChainRemovedSetRequest.Size(m)
}
func (m *UnmapMarkDiskChainRemovedSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnmapMarkDiskChainRemovedSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnmapMarkDiskChainRemovedSetRequest proto.InternalMessageInfo

func (m *UnmapMarkDiskChainRemovedSetRequest) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

type UnmapMarkDiskChainRemovedSetResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnmapMarkDiskChainRemovedSetResponse) Reset()         { *m = UnmapMarkDiskChainRemovedSetResponse{} }
func (m *UnmapMarkDiskChainRemovedSetResponse) String() string { return proto.CompactTextString(m) }
func (*UnmapMarkDiskChainRemovedSetResponse) ProtoMessage()    {}
func (*UnmapMarkDiskChainRemovedSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{25}
}

func (m *UnmapMarkDiskChainRemovedSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnmapMarkDiskChainRemovedSetResponse.Unmarshal(m, b)
}
func (m *UnmapMarkDiskChainRemovedSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnmapMarkDiskChainRemovedSetResponse.Marshal(b, m, deterministic)
}
func (m *UnmapMarkDiskChainRemovedSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnmapMarkDiskChainRemovedSetResponse.Merge(m, src)
}
func (m *UnmapMarkDiskChainRemovedSetResponse) XXX_Size() int {
	return xxx_messageInfo_UnmapMarkDiskChainRemovedSetResponse.Size(m)
}
func (m *UnmapMarkDiskChainRemovedSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnmapMarkDiskChainRemovedSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnmapMarkDiskChainRemovedSetResponse proto.InternalMessageInfo

func (m *UnmapMarkDiskChainRemovedSetResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type MaximumSnapshotCountSetRequest struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaximumSnapshotCountSetRequest) Reset()         { *m = MaximumSnapshotCountSetRequest{} }
func (m *MaximumSnapshotCountSetRequest) String() string { return proto.CompactTextString(m) }
func (*MaximumSnapshotCountSetRequest) ProtoMessage()    {}
func (*MaximumSnapshotCountSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{26}
}

func (m *MaximumSnapshotCountSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaximumSnapshotCountSetRequest.Unmarshal(m, b)
}
func (m *MaximumSnapshotCountSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaximumSnapshotCountSetRequest.Marshal(b, m, deterministic)
}
func (m *MaximumSnapshotCountSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaximumSnapshotCountSetRequest.Merge(m, src)
}
func (m *MaximumSnapshotCountSetRequest) XXX_Size() int {
	return xxx_messageInfo_MaximumSnapshotCountSetRequest.Size(m)
}
func (m *MaximumSnapshotCountSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MaximumSnapshotCountSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MaximumSnapshotCountSetRequest proto.InternalMessageInfo

func (m *MaximumSnapshotCountSetRequest) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type MaximumSnapshotCountSetResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaximumSnapshotCountSetResponse) Reset()         { *m = MaximumSnapshotCountSetResponse{} }
func (m *MaximumSnapshotCountSetResponse) String() string { return proto.CompactTextString(m) }
func (*MaximumSnapshotCountSetResponse) ProtoMessage()    {}
func (*MaximumSnapshotCountSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{27}
}

func (m *MaximumSnapshotCountSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaximumSnapshotCountSetResponse.Unmarshal(m, b)
}
func (m *MaximumSnapshotCountSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaximumSnapshotCountSetResponse.Marshal(b, m, deterministic)
}
func (m *MaximumSnapshotCountSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaximumSnapshotCountSetResponse.Merge(m, src)
}
func (m *MaximumSnapshotCountSetResponse) XXX_Size() int {
	return xxx_messageInfo_MaximumSnapshotCountSetResponse.Size(m)
}
func (m *MaximumSnapshotCountSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MaximumSnapshotCountSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MaximumSnapshotCountSetResponse proto.InternalMessageInfo

func (m *MaximumSnapshotCountSetResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type MaximumTotalSnapshotSizeSetRequest struct {
	Size                 int64    `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaximumTotalSnapshotSizeSetRequest) Reset()         { *m = MaximumTotalSnapshotSizeSetRequest{} }
func (m *MaximumTotalSnapshotSizeSetRequest) String() string { return proto.CompactTextString(m) }
func (*MaximumTotalSnapshotSizeSetRequest) ProtoMessage()    {}
func (*MaximumTotalSnapshotSizeSetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{28}
}

func (m *MaximumTotalSnapshotSizeSetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaximumTotalSnapshotSizeSetRequest.Unmarshal(m, b)
}
func (m *MaximumTotalSnapshotSizeSetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaximumTotalSnapshotSizeSetRequest.Marshal(b, m, deterministic)
}
func (m *MaximumTotalSnapshotSizeSetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaximumTotalSnapshotSizeSetRequest.Merge(m, src)
}
func (m *MaximumTotalSnapshotSizeSetRequest) XXX_Size() int {
	return xxx_messageInfo_MaximumTotalSnapshotSizeSetRequest.Size(m)
}
func (m *MaximumTotalSnapshotSizeSetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MaximumTotalSnapshotSizeSetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MaximumTotalSnapshotSizeSetRequest proto.InternalMessageInfo

func (m *MaximumTotalSnapshotSizeSetRequest) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type MaximumTotalSnapshotSizeSetResponse struct {
	Replica              *Replica `protobuf:"bytes,1,opt,name=replica,proto3" json:"replica,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaximumTotalSnapshotSizeSetResponse) Reset()         { *m = MaximumTotalSnapshotSizeSetResponse{} }
func (m *MaximumTotalSnapshotSizeSetResponse) String() string { return proto.CompactTextString(m) }
func (*MaximumTotalSnapshotSizeSetResponse) ProtoMessage()    {}
func (*MaximumTotalSnapshotSizeSetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{29}
}

func (m *MaximumTotalSnapshotSizeSetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaximumTotalSnapshotSizeSetResponse.Unmarshal(m, b)
}
func (m *MaximumTotalSnapshotSizeSetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaximumTotalSnapshotSizeSetResponse.Marshal(b, m, deterministic)
}
func (m *MaximumTotalSnapshotSizeSetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaximumTotalSnapshotSizeSetResponse.Merge(m, src)
}
func (m *MaximumTotalSnapshotSizeSetResponse) XXX_Size() int {
	return xxx_messageInfo_MaximumTotalSnapshotSizeSetResponse.Size(m)
}
func (m *MaximumTotalSnapshotSizeSetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MaximumTotalSnapshotSizeSetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MaximumTotalSnapshotSizeSetResponse proto.InternalMessageInfo

func (m *MaximumTotalSnapshotSizeSetResponse) GetReplica() *Replica {
	if m != nil {
		return m.Replica
	}
	return nil
}

type DiskInfo struct {
	Name                 string            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Parent               string            `protobuf:"bytes,2,opt,name=parent,proto3" json:"parent,omitempty"`
	Children             map[string]bool   `protobuf:"bytes,3,rep,name=children,proto3" json:"children,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	Removed              bool              `protobuf:"varint,4,opt,name=removed,proto3" json:"removed,omitempty"`
	UserCreated          bool              `protobuf:"varint,5,opt,name=user_created,json=userCreated,proto3" json:"user_created,omitempty"`
	Created              string            `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	Size                 string            `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`
	Labels               map[string]string `protobuf:"bytes,8,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *DiskInfo) Reset()         { *m = DiskInfo{} }
func (m *DiskInfo) String() string { return proto.CompactTextString(m) }
func (*DiskInfo) ProtoMessage()    {}
func (*DiskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{30}
}

func (m *DiskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiskInfo.Unmarshal(m, b)
}
func (m *DiskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiskInfo.Marshal(b, m, deterministic)
}
func (m *DiskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiskInfo.Merge(m, src)
}
func (m *DiskInfo) XXX_Size() int {
	return xxx_messageInfo_DiskInfo.Size(m)
}
func (m *DiskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_DiskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_DiskInfo proto.InternalMessageInfo

func (m *DiskInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DiskInfo) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *DiskInfo) GetChildren() map[string]bool {
	if m != nil {
		return m.Children
	}
	return nil
}

func (m *DiskInfo) GetRemoved() bool {
	if m != nil {
		return m.Removed
	}
	return false
}

func (m *DiskInfo) GetUserCreated() bool {
	if m != nil {
		return m.UserCreated
	}
	return false
}

func (m *DiskInfo) GetCreated() string {
	if m != nil {
		return m.Created
	}
	return ""
}

func (m *DiskInfo) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *DiskInfo) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type Replica struct {
	Dirty                     bool                 `protobuf:"varint,1,opt,name=dirty,proto3" json:"dirty,omitempty"`
	Rebuilding                bool                 `protobuf:"varint,2,opt,name=rebuilding,proto3" json:"rebuilding,omitempty"`
	Head                      string               `protobuf:"bytes,3,opt,name=head,proto3" json:"head,omitempty"`
	Parent                    string               `protobuf:"bytes,4,opt,name=parent,proto3" json:"parent,omitempty"`
	Size                      string               `protobuf:"bytes,5,opt,name=size,proto3" json:"size,omitempty"`
	SectorSize                int64                `protobuf:"varint,6,opt,name=sector_size,json=sectorSize,proto3" json:"sector_size,omitempty"`
	BackingFile               string               `protobuf:"bytes,7,opt,name=backing_file,json=backingFile,proto3" json:"backing_file,omitempty"`
	State                     string               `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	Chain                     []string             `protobuf:"bytes,9,rep,name=chain,proto3" json:"chain,omitempty"`
	Disks                     map[string]*DiskInfo `protobuf:"bytes,10,rep,name=disks,proto3" json:"disks,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	RemainSnapshots           int32                `protobuf:"varint,11,opt,name=remain_snapshots,json=remainSnapshots,proto3" json:"remain_snapshots,omitempty"`
	RevisionCounter           int64                `protobuf:"varint,12,opt,name=revision_counter,json=revisionCounter,proto3" json:"revision_counter,omitempty"`
	LastModifyTime            int64                `protobuf:"varint,13,opt,name=last_modify_time,json=lastModifyTime,proto3" json:"last_modify_time,omitempty"`
	HeadFileSize              int64                `protobuf:"varint,14,opt,name=head_file_size,json=headFileSize,proto3" json:"head_file_size,omitempty"`
	RevisionCounterDisabled   bool                 `protobuf:"varint,15,opt,name=revision_counter_disabled,json=revisionCounterDisabled,proto3" json:"revision_counter_disabled,omitempty"`
	UnmapMarkDiskChainRemoved bool                 `protobuf:"varint,16,opt,name=unmap_mark_disk_chain_removed,json=unmapMarkDiskChainRemoved,proto3" json:"unmap_mark_disk_chain_removed,omitempty"`
	SnapshotCountUsage        int32                `protobuf:"varint,17,opt,name=snapshot_count_usage,json=snapshotCountUsage,proto3" json:"snapshot_count_usage,omitempty"`
	SnapshotSizeUsage         int64                `protobuf:"varint,18,opt,name=snapshot_size_usage,json=snapshotSizeUsage,proto3" json:"snapshot_size_usage,omitempty"`
	XXX_NoUnkeyedLiteral      struct{}             `json:"-"`
	XXX_unrecognized          []byte               `json:"-"`
	XXX_sizecache             int32                `json:"-"`
}

func (m *Replica) Reset()         { *m = Replica{} }
func (m *Replica) String() string { return proto.CompactTextString(m) }
func (*Replica) ProtoMessage()    {}
func (*Replica) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{31}
}

func (m *Replica) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Replica.Unmarshal(m, b)
}
func (m *Replica) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Replica.Marshal(b, m, deterministic)
}
func (m *Replica) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Replica.Merge(m, src)
}
func (m *Replica) XXX_Size() int {
	return xxx_messageInfo_Replica.Size(m)
}
func (m *Replica) XXX_DiscardUnknown() {
	xxx_messageInfo_Replica.DiscardUnknown(m)
}

var xxx_messageInfo_Replica proto.InternalMessageInfo

func (m *Replica) GetDirty() bool {
	if m != nil {
		return m.Dirty
	}
	return false
}

func (m *Replica) GetRebuilding() bool {
	if m != nil {
		return m.Rebuilding
	}
	return false
}

func (m *Replica) GetHead() string {
	if m != nil {
		return m.Head
	}
	return ""
}

func (m *Replica) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *Replica) GetSize() string {
	if m != nil {
		return m.Size
	}
	return ""
}

func (m *Replica) GetSectorSize() int64 {
	if m != nil {
		return m.SectorSize
	}
	return 0
}

func (m *Replica) GetBackingFile() string {
	if m != nil {
		return m.BackingFile
	}
	return ""
}

func (m *Replica) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Replica) GetChain() []string {
	if m != nil {
		return m.Chain
	}
	return nil
}

func (m *Replica) GetDisks() map[string]*DiskInfo {
	if m != nil {
		return m.Disks
	}
	return nil
}

func (m *Replica) GetRemainSnapshots() int32 {
	if m != nil {
		return m.RemainSnapshots
	}
	return 0
}

func (m *Replica) GetRevisionCounter() int64 {
	if m != nil {
		return m.RevisionCounter
	}
	return 0
}

func (m *Replica) GetLastModifyTime() int64 {
	if m != nil {
		return m.LastModifyTime
	}
	return 0
}

func (m *Replica) GetHeadFileSize() int64 {
	if m != nil {
		return m.HeadFileSize
	}
	return 0
}

func (m *Replica) GetRevisionCounterDisabled() bool {
	if m != nil {
		return m.RevisionCounterDisabled
	}
	return false
}

func (m *Replica) GetUnmapMarkDiskChainRemoved() bool {
	if m != nil {
		return m.UnmapMarkDiskChainRemoved
	}
	return false
}

func (m *Replica) GetSnapshotCountUsage() int32 {
	if m != nil {
		return m.SnapshotCountUsage
	}
	return 0
}

func (m *Replica) GetSnapshotSizeUsage() int64 {
	if m != nil {
		return m.SnapshotSizeUsage
	}
	return 0
}

type PrepareRemoveAction struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	Source               string   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Target               string   `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareRemoveAction) Reset()         { *m = PrepareRemoveAction{} }
func (m *PrepareRemoveAction) String() string { return proto.CompactTextString(m) }
func (*PrepareRemoveAction) ProtoMessage()    {}
func (*PrepareRemoveAction) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e84aa831fb48ea1, []int{32}
}

func (m *PrepareRemoveAction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareRemoveAction.Unmarshal(m, b)
}
func (m *PrepareRemoveAction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareRemoveAction.Marshal(b, m, deterministic)
}
func (m *PrepareRemoveAction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareRemoveAction.Merge(m, src)
}
func (m *PrepareRemoveAction) XXX_Size() int {
	return xxx_messageInfo_PrepareRemoveAction.Size(m)
}
func (m *PrepareRemoveAction) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareRemoveAction.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareRemoveAction proto.InternalMessageInfo

func (m *PrepareRemoveAction) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *PrepareRemoveAction) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *PrepareRemoveAction) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

func init() {
	proto.RegisterType((*ReplicaCreateRequest)(nil), "ptypes.ReplicaCreateRequest")
	proto.RegisterType((*ReplicaCreateResponse)(nil), "ptypes.ReplicaCreateResponse")
	proto.RegisterType((*ReplicaGetResponse)(nil), "ptypes.ReplicaGetResponse")
	proto.RegisterType((*ReplicaOpenResponse)(nil), "ptypes.ReplicaOpenResponse")
	proto.RegisterType((*ReplicaCloseResponse)(nil), "ptypes.ReplicaCloseResponse")
	proto.RegisterType((*ReplicaReloadResponse)(nil), "ptypes.ReplicaReloadResponse")
	proto.RegisterType((*ReplicaRevertRequest)(nil), "ptypes.ReplicaRevertRequest")
	proto.RegisterType((*ReplicaRevertResponse)(nil), "ptypes.ReplicaRevertResponse")
	proto.RegisterType((*ReplicaSnapshotRequest)(nil), "ptypes.ReplicaSnapshotRequest")
	proto.RegisterMapType((map[string]string)(nil), "ptypes.ReplicaSnapshotRequest.LabelsEntry")
	proto.RegisterType((*ReplicaSnapshotResponse)(nil), "ptypes.ReplicaSnapshotResponse")
	proto.RegisterType((*ReplicaExpandRequest)(nil), "ptypes.ReplicaExpandRequest")
	proto.RegisterType((*ReplicaExpandResponse)(nil), "ptypes.ReplicaExpandResponse")
	proto.RegisterType((*DiskRemoveRequest)(nil), "ptypes.DiskRemoveRequest")
	proto.RegisterType((*DiskRemoveResponse)(nil), "ptypes.DiskRemoveResponse")
	proto.RegisterType((*DiskReplaceRequest)(nil), "ptypes.DiskReplaceRequest")
	proto.RegisterType((*DiskReplaceResponse)(nil), "ptypes.DiskReplaceResponse")
	proto.RegisterType((*DiskPrepareRemoveRequest)(nil), "ptypes.DiskPrepareRemoveRequest")
	proto.RegisterType((*DiskPrepareRemoveResponse)(nil), "ptypes.DiskPrepareRemoveResponse")
	proto.RegisterType((*DiskMarkAsRemovedRequest)(nil), "ptypes.DiskMarkAsRemovedRequest")
	proto.RegisterType((*DiskMarkAsRemovedResponse)(nil), "ptypes.DiskMarkAsRemovedResponse")
	proto.RegisterType((*RebuildingSetRequest)(nil), "ptypes.RebuildingSetRequest")
	proto.RegisterType((*RebuildingSetResponse)(nil), "ptypes.RebuildingSetResponse")
	proto.RegisterType((*RevisionCounterSetRequest)(nil), "ptypes.RevisionCounterSetRequest")
	proto.RegisterType((*RevisionCounterSetResponse)(nil), "ptypes.RevisionCounterSetResponse")
	proto.RegisterType((*UnmapMarkDiskChainRemovedSetRequest)(nil), "ptypes.UnmapMarkDiskChainRemovedSetRequest")
	proto.RegisterType((*UnmapMarkDiskChainRemovedSetResponse)(nil), "ptypes.UnmapMarkDiskChainRemovedSetResponse")
	proto.RegisterType((*MaximumSnapshotCountSetRequest)(nil), "ptypes.MaximumSnapshotCountSetRequest")
	proto.RegisterType((*MaximumSnapshotCountSetResponse)(nil), "ptypes.MaximumSnapshotCountSetResponse")
	proto.RegisterType((*MaximumTotalSnapshotSizeSetRequest)(nil), "ptypes.MaximumTotalSnapshotSizeSetRequest")
	proto.RegisterType((*MaximumTotalSnapshotSizeSetResponse)(nil), "ptypes.MaximumTotalSnapshotSizeSetResponse")
	proto.RegisterType((*DiskInfo)(nil), "ptypes.DiskInfo")
	proto.RegisterMapType((map[string]bool)(nil), "ptypes.DiskInfo.ChildrenEntry")
	proto.RegisterMapType((map[string]string)(nil), "ptypes.DiskInfo.LabelsEntry")
	proto.RegisterType((*Replica)(nil), "ptypes.Replica")
	proto.RegisterMapType((map[string]*DiskInfo)(nil), "ptypes.Replica.DisksEntry")
	proto.RegisterType((*PrepareRemoveAction)(nil), "ptypes.PrepareRemoveAction")
}

func init() { proto.RegisterFile("replica.proto", fileDescriptor_1e84aa831fb48ea1) }

var fileDescriptor_1e84aa831fb48ea1 = []byte{
	// 1389 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xe9, 0x6e, 0xdb, 0x46,
	0x10, 0x96, 0x23, 0x4b, 0x56, 0x46, 0xbe, 0xb2, 0x71, 0x1d, 0x9a, 0x4e, 0x1c, 0x87, 0x09, 0xd2,
	0x1c, 0x85, 0x12, 0xb8, 0x07, 0x52, 0x07, 0x45, 0x63, 0x5b, 0x76, 0xda, 0x22, 0x6e, 0x53, 0xda,
	0x01, 0x8a, 0x02, 0x01, 0xb1, 0x92, 0xd6, 0x32, 0x21, 0x8a, 0x64, 0xb9, 0x94, 0x61, 0xa5, 0x8f,
	0xd0, 0x7f, 0x7d, 0xca, 0xfe, 0xef, 0x0b, 0x14, 0x7b, 0x51, 0x4b, 0x8a, 0xa2, 0x2d, 0xf5, 0x1f,
	0x77, 0x38, 0x3b, 0xfb, 0xed, 0x37, 0xc7, 0xce, 0xc0, 0x52, 0x44, 0x42, 0xcf, 0x6d, 0xe3, 0x46,
	0x18, 0x05, 0x71, 0x80, 0xaa, 0x61, 0x3c, 0x0c, 0x09, 0x35, 0x37, 0xbb, 0x41, 0xd0, 0xf5, 0xc8,
	0x0b, 0x2e, 0x6d, 0x0d, 0xce, 0x5e, 0x90, 0x7e, 0x18, 0x0f, 0x85, 0x92, 0xf5, 0x0c, 0xd6, 0x6c,
	0xb1, 0xeb, 0x20, 0x22, 0x38, 0x26, 0x36, 0xf9, 0x63, 0x40, 0x68, 0x8c, 0x10, 0xcc, 0x53, 0xf7,
	0x13, 0x31, 0xe6, 0xb6, 0xe7, 0x9e, 0xdc, 0xb4, 0xf9, 0xb7, 0xb5, 0x0f, 0x9f, 0x65, 0x74, 0x69,
	0x18, 0xf8, 0x94, 0xa0, 0xa7, 0xb0, 0x20, 0x8f, 0xe6, 0xfa, 0xf5, 0x9d, 0x95, 0x86, 0x38, 0xbb,
	0x21, 0xf5, 0x6d, 0xf5, 0xdf, 0xfa, 0x1e, 0x90, 0x94, 0xbd, 0x25, 0xf1, 0x2c, 0x06, 0xde, 0xc0,
	0x6d, 0x29, 0xfb, 0x25, 0x24, 0xfe, 0x2c, 0x16, 0xf6, 0x46, 0x57, 0xf6, 0x02, 0x3a, 0xd3, 0x2d,
	0x46, 0x4c, 0xd8, 0xc4, 0x0b, 0x70, 0x67, 0x16, 0x1b, 0xcd, 0x04, 0x86, 0x4d, 0x2e, 0x48, 0x14,
	0x6b, 0xcc, 0xfb, 0xb8, 0x9f, 0x30, 0xcf, 0xbe, 0x91, 0x01, 0x0b, 0x6d, 0x4e, 0x79, 0xc7, 0xb8,
	0xc1, 0xc5, 0x6a, 0x99, 0x42, 0x22, 0xac, 0x4c, 0x8f, 0xe4, 0x9f, 0x39, 0x58, 0x97, 0xc2, 0x13,
	0x1f, 0x87, 0xf4, 0x3c, 0x28, 0x04, 0xf3, 0x00, 0x16, 0x07, 0x94, 0x44, 0x8e, 0x8e, 0xa8, 0x66,
	0xd7, 0x99, 0x4c, 0xc4, 0x45, 0x47, 0xc7, 0x5b, 0x4e, 0xe1, 0x45, 0xfb, 0x50, 0xf5, 0x70, 0x8b,
	0x78, 0xd4, 0x98, 0xdf, 0x2e, 0x3f, 0xa9, 0xef, 0x3c, 0xcb, 0xa0, 0xca, 0x00, 0x68, 0xbc, 0xe3,
	0xca, 0x87, 0x7e, 0x1c, 0x0d, 0x6d, 0xb9, 0xd3, 0xfc, 0x16, 0xea, 0x9a, 0x18, 0xad, 0x42, 0xb9,
	0x47, 0x86, 0x12, 0x22, 0xfb, 0x44, 0x6b, 0x50, 0xb9, 0xc0, 0xde, 0x80, 0x48, 0xb2, 0xc4, 0x62,
	0xf7, 0xc6, 0xab, 0x39, 0xab, 0x09, 0x77, 0xc6, 0x0e, 0x9a, 0x9e, 0xb0, 0x51, 0xd2, 0x1c, 0x5e,
	0x86, 0xd8, 0xef, 0xe4, 0x25, 0x4d, 0x79, 0x2c, 0x69, 0x94, 0xee, 0xf4, 0xe7, 0x7d, 0x07, 0xb7,
	0x9a, 0x2e, 0xed, 0xd9, 0xa4, 0x1f, 0x5c, 0x90, 0x22, 0xd7, 0xac, 0x41, 0xe5, 0x2c, 0x88, 0xda,
	0x44, 0xfa, 0x44, 0x2c, 0x58, 0xce, 0xe9, 0xdb, 0x67, 0x09, 0x55, 0x69, 0x20, 0xf4, 0x70, 0x3b,
	0x01, 0xb0, 0x0e, 0xd5, 0x18, 0x47, 0x5d, 0x12, 0x4b, 0x08, 0x72, 0xc5, 0xe4, 0x34, 0x18, 0x28,
	0x14, 0x37, 0x6d, 0xb9, 0x62, 0x99, 0x9b, 0xb2, 0x32, 0x3d, 0x8e, 0x06, 0x18, 0xcc, 0xc2, 0xfb,
	0x88, 0x84, 0x38, 0x22, 0x57, 0xd2, 0x61, 0xfd, 0x06, 0x1b, 0x39, 0xfa, 0xf2, 0xdc, 0xd7, 0x00,
	0x41, 0x48, 0x22, 0x1c, 0xbb, 0x81, 0x4f, 0x8d, 0x39, 0x1e, 0x8d, 0x9b, 0xea, 0xe8, 0xd4, 0x96,
	0xbd, 0x36, 0xd3, 0xb1, 0x35, 0x75, 0x85, 0xe4, 0x18, 0x47, 0xbd, 0x3d, 0x2a, 0xb4, 0x3a, 0x45,
	0x48, 0x8e, 0x04, 0x92, 0x8c, 0xfe, 0xf4, 0x0c, 0x7c, 0xc3, 0x22, 0xaf, 0x35, 0x70, 0xbd, 0x8e,
	0xeb, 0x77, 0x4f, 0x48, 0x92, 0xa7, 0x5b, 0x00, 0x51, 0x22, 0xe7, 0x56, 0x6a, 0xb6, 0x26, 0x11,
	0x51, 0x98, 0xda, 0x37, 0xfd, 0xd9, 0x5f, 0xc3, 0x86, 0x4d, 0x2e, 0x5c, 0xea, 0x06, 0xfe, 0x41,
	0x30, 0xf0, 0x63, 0x12, 0x69, 0x00, 0x58, 0xc6, 0x0b, 0xa1, 0x8c, 0x7e, 0xb5, 0xb4, 0xde, 0x82,
	0x99, 0xb7, 0x6d, 0x96, 0xa7, 0xe3, 0xe1, 0x07, 0xbf, 0x8f, 0x43, 0x46, 0x22, 0x23, 0xf3, 0xe0,
	0x1c, 0xbb, 0xbe, 0xe4, 0x32, 0x8d, 0x84, 0xf8, 0xb8, 0xe5, 0x91, 0x8e, 0xe4, 0x41, 0x2d, 0xad,
	0x5f, 0xe1, 0x51, 0xb1, 0x81, 0x59, 0xfc, 0xb1, 0x75, 0x8c, 0x2f, 0xdd, 0xfe, 0xa0, 0xaf, 0xea,
	0x09, 0xbf, 0xa3, 0x06, 0x67, 0x0d, 0x2a, 0x9c, 0x09, 0x6e, 0xaa, 0x62, 0x8b, 0x85, 0xf5, 0x0e,
	0xee, 0x4f, 0xdc, 0x37, 0x3d, 0x8a, 0x57, 0x60, 0x49, 0x6b, 0xa7, 0x41, 0x8c, 0x3d, 0x65, 0xf2,
	0xc4, 0xfd, 0x44, 0x34, 0x24, 0x79, 0xd5, 0xe9, 0x3d, 0x3c, 0x2c, 0xdc, 0x39, 0x3d, 0x96, 0xbf,
	0xca, 0x50, 0x63, 0xe4, 0xfe, 0xe8, 0x9f, 0x05, 0xb9, 0x35, 0x6a, 0x1d, 0xaa, 0x2c, 0xb5, 0xfc,
	0x58, 0x95, 0x07, 0xb1, 0x42, 0xbb, 0x50, 0x6b, 0x9f, 0xbb, 0x5e, 0x27, 0x22, 0xbe, 0x51, 0xe6,
	0xd9, 0xb8, 0xa5, 0x0e, 0x51, 0xf6, 0x1a, 0x07, 0x52, 0x41, 0xbc, 0x07, 0x89, 0x3e, 0xf3, 0x79,
	0x24, 0xfc, 0x68, 0xcc, 0x0b, 0x9f, 0xcb, 0xe5, 0xd8, 0x63, 0x55, 0x29, 0x7c, 0xac, 0xaa, 0xe9,
	0xc7, 0x4a, 0x31, 0xb6, 0x30, 0x6a, 0x82, 0xd0, 0x57, 0xc9, 0x03, 0x56, 0xe3, 0x20, 0xef, 0x8e,
	0x81, 0xcc, 0x7b, 0xb2, 0x5e, 0xc3, 0x52, 0x0a, 0xfb, 0x55, 0x8f, 0x56, 0x4d, 0x7b, 0xb4, 0xfe,
	0xcf, 0x7b, 0xf7, 0x6f, 0x05, 0x16, 0xa4, 0x8b, 0x98, 0x56, 0xc7, 0x8d, 0xe2, 0xa1, 0x4c, 0x0b,
	0xb1, 0xc8, 0x54, 0x8e, 0x1b, 0xd9, 0xca, 0xc1, 0x38, 0x38, 0x27, 0x58, 0xbd, 0xe3, 0xfc, 0x5b,
	0x73, 0xe1, 0x7c, 0xca, 0x85, 0x8a, 0xaf, 0x8a, 0xc6, 0xd7, 0x7d, 0xa8, 0x53, 0xd2, 0x8e, 0x83,
	0xc8, 0xe1, 0xbf, 0xaa, 0x3c, 0xf8, 0x40, 0x88, 0x58, 0x98, 0x31, 0x0f, 0xb5, 0x70, 0xbb, 0xe7,
	0xfa, 0x5d, 0xe7, 0xcc, 0xf5, 0x14, 0xd9, 0x75, 0x29, 0x3b, 0x72, 0x3d, 0xfe, 0xac, 0xd1, 0x18,
	0xc7, 0xc4, 0xa8, 0x89, 0xfb, 0xf1, 0x05, 0xcf, 0x2c, 0x96, 0xc1, 0xc6, 0xcd, 0xed, 0x32, 0x93,
	0xf2, 0x05, 0x7a, 0xc9, 0x6e, 0x49, 0x7b, 0xd4, 0x00, 0xee, 0x1e, 0x33, 0x13, 0xa8, 0xdc, 0x4d,
	0xd2, 0x39, 0x42, 0x11, 0x3d, 0x85, 0xd5, 0x88, 0xf4, 0xb1, 0xeb, 0x3b, 0x54, 0x86, 0x3f, 0x35,
	0xea, 0x3c, 0x59, 0x57, 0x84, 0x5c, 0x65, 0x85, 0x54, 0x15, 0xb5, 0xcc, 0x51, 0xe5, 0x6e, 0x91,
	0xdf, 0x68, 0x25, 0x4a, 0xd7, 0x38, 0xf4, 0x04, 0x56, 0x3d, 0x4c, 0x63, 0xa7, 0x1f, 0x74, 0xdc,
	0xb3, 0xa1, 0x13, 0xbb, 0x7d, 0x62, 0x2c, 0x71, 0xd5, 0x65, 0x26, 0x3f, 0xe6, 0xe2, 0x53, 0xb7,
	0x4f, 0xd0, 0x23, 0x58, 0x66, 0xac, 0xf2, 0xdb, 0x0b, 0x92, 0x96, 0xb9, 0xde, 0x22, 0x93, 0xb2,
	0xfb, 0x73, 0x9a, 0x76, 0x61, 0x23, 0x7b, 0xb4, 0xd3, 0x71, 0xa9, 0x28, 0x74, 0x2b, 0xdc, 0x6d,
	0x77, 0x32, 0x18, 0x9a, 0xf2, 0x37, 0x7a, 0x03, 0xf7, 0x06, 0xac, 0xf0, 0x39, 0x7d, 0x1c, 0xf5,
	0xd8, 0xae, 0x9e, 0xc3, 0xc9, 0x72, 0x54, 0xd2, 0xac, 0xf2, 0xfd, 0x1b, 0x83, 0x49, 0xd5, 0x11,
	0xbd, 0x84, 0x35, 0x45, 0x8e, 0x38, 0xdd, 0x19, 0x50, 0xdc, 0x25, 0xc6, 0x2d, 0xce, 0x13, 0xa2,
	0x7a, 0x11, 0xfb, 0xc0, 0xfe, 0xa0, 0x06, 0xdc, 0x4e, 0x76, 0xb0, 0x4b, 0xc9, 0x0d, 0x88, 0x5f,
	0xed, 0x16, 0xd5, 0x0a, 0x0d, 0xd7, 0x37, 0x7f, 0x02, 0x18, 0xb9, 0x26, 0x27, 0xc6, 0x1f, 0xeb,
	0x31, 0x5e, 0xdf, 0x59, 0xcd, 0xa6, 0x9d, 0x1e, 0xf5, 0x1f, 0xe1, 0x76, 0xce, 0x03, 0xce, 0xc2,
	0x16, 0xf3, 0x2f, 0xd5, 0xb0, 0xe0, 0x44, 0x9e, 0xd7, 0xb0, 0x68, 0x0d, 0x4e, 0x59, 0x6f, 0x70,
	0x76, 0xfe, 0x5e, 0x84, 0x65, 0xd5, 0x45, 0x92, 0xe8, 0xc2, 0x6d, 0x13, 0xf4, 0x33, 0x2c, 0xa5,
	0x46, 0x23, 0x74, 0x37, 0x13, 0x77, 0xa9, 0xe9, 0xca, 0xbc, 0x37, 0xe1, 0xaf, 0x28, 0xb7, 0x56,
	0x09, 0xed, 0x25, 0xf6, 0x9a, 0xc4, 0x23, 0x31, 0x41, 0xeb, 0x0d, 0x31, 0xc5, 0x35, 0xd4, 0x14,
	0xd7, 0x38, 0x64, 0x53, 0x9c, 0x39, 0x41, 0x6e, 0x95, 0xd0, 0x3e, 0xc0, 0x68, 0xd2, 0x9a, 0xb8,
	0x3f, 0x9b, 0x1f, 0xda, 0x54, 0x66, 0x95, 0x50, 0x13, 0xea, 0xda, 0xb0, 0x35, 0xd1, 0xc8, 0x66,
	0xc6, 0x88, 0x3e, 0x99, 0x59, 0x25, 0x74, 0x04, 0x8b, 0xfa, 0xc0, 0x35, 0xd1, 0xcc, 0x18, 0x67,
	0xfa, 0x78, 0x66, 0x95, 0xd0, 0x0f, 0x09, 0x29, 0x62, 0xea, 0x9a, 0x68, 0x28, 0x4b, 0x6f, 0x7a,
	0x48, 0xb3, 0x4a, 0x9a, 0xbb, 0xc4, 0xd4, 0x34, 0xe6, 0xae, 0xd4, 0x48, 0x96, 0x63, 0x4f, 0x1f,
	0xb5, 0xac, 0x12, 0x3a, 0x85, 0x95, 0xcc, 0x58, 0x81, 0xb6, 0x8a, 0x07, 0x1b, 0xf3, 0xfe, 0xc4,
	0xff, 0x39, 0x28, 0xc5, 0xe8, 0x30, 0x86, 0x32, 0x35, 0x7d, 0x8c, 0xa1, 0x4c, 0xcf, 0x1b, 0x56,
	0x09, 0x1d, 0x8a, 0x14, 0x13, 0x39, 0x81, 0x36, 0xf4, 0x0c, 0x4a, 0xf5, 0xd2, 0xa3, 0xa0, 0x18,
	0x1f, 0x1b, 0xb8, 0x1b, 0xea, 0x5a, 0x1f, 0x8f, 0x32, 0xca, 0xfa, 0x88, 0x30, 0x0a, 0x8c, 0x9c,
	0xc6, 0xdf, 0x2a, 0xa1, 0xdf, 0xc5, 0x5c, 0x93, 0xca, 0x55, 0xb4, 0xad, 0xef, 0xc9, 0x6b, 0xf5,
	0xcd, 0x07, 0x05, 0x1a, 0x59, 0xdb, 0xa9, 0x8e, 0x3b, 0x6d, 0x3b, 0xaf, 0x79, 0x4f, 0xdb, 0xce,
	0x6d, 0xd7, 0x95, 0x63, 0xb4, 0x6e, 0x5a, 0x77, 0xcc, 0x78, 0x73, 0xae, 0x3b, 0x26, 0xa7, 0x05,
	0xb7, 0x4a, 0xe8, 0x23, 0xa0, 0xf1, 0x16, 0x19, 0x3d, 0x18, 0x6d, 0x9b, 0xd0, 0x75, 0x9b, 0x56,
	0x91, 0x4a, 0x62, 0xfe, 0x4f, 0xb8, 0x5b, 0xd4, 0xf7, 0xa2, 0xe7, 0xca, 0xca, 0x35, 0xda, 0x6b,
	0xf3, 0x8b, 0xeb, 0x29, 0x27, 0x87, 0x7b, 0x70, 0x67, 0x42, 0xa7, 0x8b, 0x1e, 0x2b, 0x53, 0xc5,
	0x2d, 0xb4, 0xf9, 0xf9, 0x95, 0x7a, 0xc9, 0x69, 0x97, 0xb0, 0x59, 0xd0, 0xcf, 0xa2, 0x67, 0x19,
	0x4b, 0x05, 0xed, 0xb2, 0xf9, 0xfc, 0x5a, 0xba, 0xea, 0xe4, 0x56, 0x95, 0xd7, 0xa0, 0x2f, 0xff,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x27, 0xf8, 0x5a, 0x4b, 0x85, 0x13, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ReplicaServiceClient is the client API for ReplicaService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ReplicaServiceClient interface {
	ReplicaCreate(ctx context.Context, in *ReplicaCreateRequest, opts ...grpc.CallOption) (*ReplicaCreateResponse, error)
	ReplicaDelete(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	ReplicaGet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReplicaGetResponse, error)
	ReplicaOpen(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReplicaOpenResponse, error)
	ReplicaClose(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReplicaCloseResponse, error)
	ReplicaReload(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReplicaReloadResponse, error)
	ReplicaRevert(ctx context.Context, in *ReplicaRevertRequest, opts ...grpc.CallOption) (*ReplicaRevertResponse, error)
	ReplicaSnapshot(ctx context.Context, in *ReplicaSnapshotRequest, opts ...grpc.CallOption) (*ReplicaSnapshotResponse, error)
	ReplicaExpand(ctx context.Context, in *ReplicaExpandRequest, opts ...grpc.CallOption) (*ReplicaExpandResponse, error)
	DiskRemove(ctx context.Context, in *DiskRemoveRequest, opts ...grpc.CallOption) (*DiskRemoveResponse, error)
	DiskReplace(ctx context.Context, in *DiskReplaceRequest, opts ...grpc.CallOption) (*DiskReplaceResponse, error)
	DiskPrepareRemove(ctx context.Context, in *DiskPrepareRemoveRequest, opts ...grpc.CallOption) (*DiskPrepareRemoveResponse, error)
	DiskMarkAsRemoved(ctx context.Context, in *DiskMarkAsRemovedRequest, opts ...grpc.CallOption) (*DiskMarkAsRemovedResponse, error)
	RebuildingSet(ctx context.Context, in *RebuildingSetRequest, opts ...grpc.CallOption) (*RebuildingSetResponse, error)
	RevisionCounterSet(ctx context.Context, in *RevisionCounterSetRequest, opts ...grpc.CallOption) (*RevisionCounterSetResponse, error)
	UnmapMarkDiskChainRemovedSet(ctx context.Context, in *UnmapMarkDiskChainRemovedSetRequest, opts ...grpc.CallOption) (*UnmapMarkDiskChainRemovedSetResponse, error)
	MaximumSnapshotCountSet(ctx context.Context, in *MaximumSnapshotCountSetRequest, opts ...grpc.CallOption) (*MaximumSnapshotCountSetResponse, error)
	MaximumTotalSnapshotSizeSet(ctx context.Context, in *MaximumTotalSnapshotSizeSetRequest, opts ...grpc.CallOption) (*MaximumTotalSnapshotSizeSetResponse, error)
}

type replicaServiceClient struct {
	cc *grpc.ClientConn
}

func NewReplicaServiceClient(cc *grpc.ClientConn) ReplicaServiceClient {
	return &replicaServiceClient{cc}
}

func (c *replicaServiceClient) ReplicaCreate(ctx context.Context, in *ReplicaCreateRequest, opts ...grpc.CallOption) (*ReplicaCreateResponse, error) {
	out := new(ReplicaCreateResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/ReplicaCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) ReplicaDelete(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/ReplicaDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) ReplicaGet(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReplicaGetResponse, error) {
	out := new(ReplicaGetResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/ReplicaGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) ReplicaOpen(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReplicaOpenResponse, error) {
	out := new(ReplicaOpenResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/ReplicaOpen", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) ReplicaClose(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReplicaCloseResponse, error) {
	out := new(ReplicaCloseResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/ReplicaClose", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) ReplicaReload(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*ReplicaReloadResponse, error) {
	out := new(ReplicaReloadResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/ReplicaReload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) ReplicaRevert(ctx context.Context, in *ReplicaRevertRequest, opts ...grpc.CallOption) (*ReplicaRevertResponse, error) {
	out := new(ReplicaRevertResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/ReplicaRevert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) ReplicaSnapshot(ctx context.Context, in *ReplicaSnapshotRequest, opts ...grpc.CallOption) (*ReplicaSnapshotResponse, error) {
	out := new(ReplicaSnapshotResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/ReplicaSnapshot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) ReplicaExpand(ctx context.Context, in *ReplicaExpandRequest, opts ...grpc.CallOption) (*ReplicaExpandResponse, error) {
	out := new(ReplicaExpandResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/ReplicaExpand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) DiskRemove(ctx context.Context, in *DiskRemoveRequest, opts ...grpc.CallOption) (*DiskRemoveResponse, error) {
	out := new(DiskRemoveResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/DiskRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) DiskReplace(ctx context.Context, in *DiskReplaceRequest, opts ...grpc.CallOption) (*DiskReplaceResponse, error) {
	out := new(DiskReplaceResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/DiskReplace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) DiskPrepareRemove(ctx context.Context, in *DiskPrepareRemoveRequest, opts ...grpc.CallOption) (*DiskPrepareRemoveResponse, error) {
	out := new(DiskPrepareRemoveResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/DiskPrepareRemove", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) DiskMarkAsRemoved(ctx context.Context, in *DiskMarkAsRemovedRequest, opts ...grpc.CallOption) (*DiskMarkAsRemovedResponse, error) {
	out := new(DiskMarkAsRemovedResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/DiskMarkAsRemoved", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) RebuildingSet(ctx context.Context, in *RebuildingSetRequest, opts ...grpc.CallOption) (*RebuildingSetResponse, error) {
	out := new(RebuildingSetResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/RebuildingSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) RevisionCounterSet(ctx context.Context, in *RevisionCounterSetRequest, opts ...grpc.CallOption) (*RevisionCounterSetResponse, error) {
	out := new(RevisionCounterSetResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/RevisionCounterSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) UnmapMarkDiskChainRemovedSet(ctx context.Context, in *UnmapMarkDiskChainRemovedSetRequest, opts ...grpc.CallOption) (*UnmapMarkDiskChainRemovedSetResponse, error) {
	out := new(UnmapMarkDiskChainRemovedSetResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/UnmapMarkDiskChainRemovedSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) MaximumSnapshotCountSet(ctx context.Context, in *MaximumSnapshotCountSetRequest, opts ...grpc.CallOption) (*MaximumSnapshotCountSetResponse, error) {
	out := new(MaximumSnapshotCountSetResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/MaximumSnapshotCountSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *replicaServiceClient) MaximumTotalSnapshotSizeSet(ctx context.Context, in *MaximumTotalSnapshotSizeSetRequest, opts ...grpc.CallOption) (*MaximumTotalSnapshotSizeSetResponse, error) {
	out := new(MaximumTotalSnapshotSizeSetResponse)
	err := c.cc.Invoke(ctx, "/ptypes.ReplicaService/MaximumTotalSnapshotSizeSet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReplicaServiceServer is the server API for ReplicaService service.
type ReplicaServiceServer interface {
	ReplicaCreate(context.Context, *ReplicaCreateRequest) (*ReplicaCreateResponse, error)
	ReplicaDelete(context.Context, *empty.Empty) (*empty.Empty, error)
	ReplicaGet(context.Context, *empty.Empty) (*ReplicaGetResponse, error)
	ReplicaOpen(context.Context, *empty.Empty) (*ReplicaOpenResponse, error)
	ReplicaClose(context.Context, *empty.Empty) (*ReplicaCloseResponse, error)
	ReplicaReload(context.Context, *empty.Empty) (*ReplicaReloadResponse, error)
	ReplicaRevert(context.Context, *ReplicaRevertRequest) (*ReplicaRevertResponse, error)
	ReplicaSnapshot(context.Context, *ReplicaSnapshotRequest) (*ReplicaSnapshotResponse, error)
	ReplicaExpand(context.Context, *ReplicaExpandRequest) (*ReplicaExpandResponse, error)
	DiskRemove(context.Context, *DiskRemoveRequest) (*DiskRemoveResponse, error)
	DiskReplace(context.Context, *DiskReplaceRequest) (*DiskReplaceResponse, error)
	DiskPrepareRemove(context.Context, *DiskPrepareRemoveRequest) (*DiskPrepareRemoveResponse, error)
	DiskMarkAsRemoved(context.Context, *DiskMarkAsRemovedRequest) (*DiskMarkAsRemovedResponse, error)
	RebuildingSet(context.Context, *RebuildingSetRequest) (*RebuildingSetResponse, error)
	RevisionCounterSet(context.Context, *RevisionCounterSetRequest) (*RevisionCounterSetResponse, error)
	UnmapMarkDiskChainRemovedSet(context.Context, *UnmapMarkDiskChainRemovedSetRequest) (*UnmapMarkDiskChainRemovedSetResponse, error)
	MaximumSnapshotCountSet(context.Context, *MaximumSnapshotCountSetRequest) (*MaximumSnapshotCountSetResponse, error)
	MaximumTotalSnapshotSizeSet(context.Context, *MaximumTotalSnapshotSizeSetRequest) (*MaximumTotalSnapshotSizeSetResponse, error)
}

// UnimplementedReplicaServiceServer can be embedded to have forward compatible implementations.
type UnimplementedReplicaServiceServer struct {
}

func (*UnimplementedReplicaServiceServer) ReplicaCreate(ctx context.Context, req *ReplicaCreateRequest) (*ReplicaCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaCreate not implemented")
}
func (*UnimplementedReplicaServiceServer) ReplicaDelete(ctx context.Context, req *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaDelete not implemented")
}
func (*UnimplementedReplicaServiceServer) ReplicaGet(ctx context.Context, req *empty.Empty) (*ReplicaGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaGet not implemented")
}
func (*UnimplementedReplicaServiceServer) ReplicaOpen(ctx context.Context, req *empty.Empty) (*ReplicaOpenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaOpen not implemented")
}
func (*UnimplementedReplicaServiceServer) ReplicaClose(ctx context.Context, req *empty.Empty) (*ReplicaCloseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaClose not implemented")
}
func (*UnimplementedReplicaServiceServer) ReplicaReload(ctx context.Context, req *empty.Empty) (*ReplicaReloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaReload not implemented")
}
func (*UnimplementedReplicaServiceServer) ReplicaRevert(ctx context.Context, req *ReplicaRevertRequest) (*ReplicaRevertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaRevert not implemented")
}
func (*UnimplementedReplicaServiceServer) ReplicaSnapshot(ctx context.Context, req *ReplicaSnapshotRequest) (*ReplicaSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaSnapshot not implemented")
}
func (*UnimplementedReplicaServiceServer) ReplicaExpand(ctx context.Context, req *ReplicaExpandRequest) (*ReplicaExpandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReplicaExpand not implemented")
}
func (*UnimplementedReplicaServiceServer) DiskRemove(ctx context.Context, req *DiskRemoveRequest) (*DiskRemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiskRemove not implemented")
}
func (*UnimplementedReplicaServiceServer) DiskReplace(ctx context.Context, req *DiskReplaceRequest) (*DiskReplaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiskReplace not implemented")
}
func (*UnimplementedReplicaServiceServer) DiskPrepareRemove(ctx context.Context, req *DiskPrepareRemoveRequest) (*DiskPrepareRemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiskPrepareRemove not implemented")
}
func (*UnimplementedReplicaServiceServer) DiskMarkAsRemoved(ctx context.Context, req *DiskMarkAsRemovedRequest) (*DiskMarkAsRemovedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiskMarkAsRemoved not implemented")
}
func (*UnimplementedReplicaServiceServer) RebuildingSet(ctx context.Context, req *RebuildingSetRequest) (*RebuildingSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RebuildingSet not implemented")
}
func (*UnimplementedReplicaServiceServer) RevisionCounterSet(ctx context.Context, req *RevisionCounterSetRequest) (*RevisionCounterSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevisionCounterSet not implemented")
}
func (*UnimplementedReplicaServiceServer) UnmapMarkDiskChainRemovedSet(ctx context.Context, req *UnmapMarkDiskChainRemovedSetRequest) (*UnmapMarkDiskChainRemovedSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnmapMarkDiskChainRemovedSet not implemented")
}
func (*UnimplementedReplicaServiceServer) MaximumSnapshotCountSet(ctx context.Context, req *MaximumSnapshotCountSetRequest) (*MaximumSnapshotCountSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaximumSnapshotCountSet not implemented")
}
func (*UnimplementedReplicaServiceServer) MaximumTotalSnapshotSizeSet(ctx context.Context, req *MaximumTotalSnapshotSizeSetRequest) (*MaximumTotalSnapshotSizeSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MaximumTotalSnapshotSizeSet not implemented")
}

func RegisterReplicaServiceServer(s *grpc.Server, srv ReplicaServiceServer) {
	s.RegisterService(&_ReplicaService_serviceDesc, srv)
}

func _ReplicaService_ReplicaCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).ReplicaCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/ReplicaCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).ReplicaCreate(ctx, req.(*ReplicaCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_ReplicaDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).ReplicaDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/ReplicaDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).ReplicaDelete(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_ReplicaGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).ReplicaGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/ReplicaGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).ReplicaGet(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_ReplicaOpen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).ReplicaOpen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/ReplicaOpen",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).ReplicaOpen(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_ReplicaClose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).ReplicaClose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/ReplicaClose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).ReplicaClose(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_ReplicaReload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).ReplicaReload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/ReplicaReload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).ReplicaReload(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_ReplicaRevert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaRevertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).ReplicaRevert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/ReplicaRevert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).ReplicaRevert(ctx, req.(*ReplicaRevertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_ReplicaSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).ReplicaSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/ReplicaSnapshot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).ReplicaSnapshot(ctx, req.(*ReplicaSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_ReplicaExpand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaExpandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).ReplicaExpand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/ReplicaExpand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).ReplicaExpand(ctx, req.(*ReplicaExpandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_DiskRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiskRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).DiskRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/DiskRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).DiskRemove(ctx, req.(*DiskRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_DiskReplace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiskReplaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).DiskReplace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/DiskReplace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).DiskReplace(ctx, req.(*DiskReplaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_DiskPrepareRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiskPrepareRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).DiskPrepareRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/DiskPrepareRemove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).DiskPrepareRemove(ctx, req.(*DiskPrepareRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_DiskMarkAsRemoved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiskMarkAsRemovedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).DiskMarkAsRemoved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/DiskMarkAsRemoved",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).DiskMarkAsRemoved(ctx, req.(*DiskMarkAsRemovedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_RebuildingSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RebuildingSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).RebuildingSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/RebuildingSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).RebuildingSet(ctx, req.(*RebuildingSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_RevisionCounterSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevisionCounterSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).RevisionCounterSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/RevisionCounterSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).RevisionCounterSet(ctx, req.(*RevisionCounterSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_UnmapMarkDiskChainRemovedSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnmapMarkDiskChainRemovedSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).UnmapMarkDiskChainRemovedSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/UnmapMarkDiskChainRemovedSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).UnmapMarkDiskChainRemovedSet(ctx, req.(*UnmapMarkDiskChainRemovedSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_MaximumSnapshotCountSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaximumSnapshotCountSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).MaximumSnapshotCountSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/MaximumSnapshotCountSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).MaximumSnapshotCountSet(ctx, req.(*MaximumSnapshotCountSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReplicaService_MaximumTotalSnapshotSizeSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MaximumTotalSnapshotSizeSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReplicaServiceServer).MaximumTotalSnapshotSizeSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ptypes.ReplicaService/MaximumTotalSnapshotSizeSet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReplicaServiceServer).MaximumTotalSnapshotSizeSet(ctx, req.(*MaximumTotalSnapshotSizeSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ReplicaService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ptypes.ReplicaService",
	HandlerType: (*ReplicaServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReplicaCreate",
			Handler:    _ReplicaService_ReplicaCreate_Handler,
		},
		{
			MethodName: "ReplicaDelete",
			Handler:    _ReplicaService_ReplicaDelete_Handler,
		},
		{
			MethodName: "ReplicaGet",
			Handler:    _ReplicaService_ReplicaGet_Handler,
		},
		{
			MethodName: "ReplicaOpen",
			Handler:    _ReplicaService_ReplicaOpen_Handler,
		},
		{
			MethodName: "ReplicaClose",
			Handler:    _ReplicaService_ReplicaClose_Handler,
		},
		{
			MethodName: "ReplicaReload",
			Handler:    _ReplicaService_ReplicaReload_Handler,
		},
		{
			MethodName: "ReplicaRevert",
			Handler:    _ReplicaService_ReplicaRevert_Handler,
		},
		{
			MethodName: "ReplicaSnapshot",
			Handler:    _ReplicaService_ReplicaSnapshot_Handler,
		},
		{
			MethodName: "ReplicaExpand",
			Handler:    _ReplicaService_ReplicaExpand_Handler,
		},
		{
			MethodName: "DiskRemove",
			Handler:    _ReplicaService_DiskRemove_Handler,
		},
		{
			MethodName: "DiskReplace",
			Handler:    _ReplicaService_DiskReplace_Handler,
		},
		{
			MethodName: "DiskPrepareRemove",
			Handler:    _ReplicaService_DiskPrepareRemove_Handler,
		},
		{
			MethodName: "DiskMarkAsRemoved",
			Handler:    _ReplicaService_DiskMarkAsRemoved_Handler,
		},
		{
			MethodName: "RebuildingSet",
			Handler:    _ReplicaService_RebuildingSet_Handler,
		},
		{
			MethodName: "RevisionCounterSet",
			Handler:    _ReplicaService_RevisionCounterSet_Handler,
		},
		{
			MethodName: "UnmapMarkDiskChainRemovedSet",
			Handler:    _ReplicaService_UnmapMarkDiskChainRemovedSet_Handler,
		},
		{
			MethodName: "MaximumSnapshotCountSet",
			Handler:    _ReplicaService_MaximumSnapshotCountSet_Handler,
		},
		{
			MethodName: "MaximumTotalSnapshotSizeSet",
			Handler:    _ReplicaService_MaximumTotalSnapshotSizeSet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "replica.proto",
}
